theme: jekyll-theme-minimal
title: DronePose
show_downloads: false
description: Photorealistic UAV-Assistant Dataset Synthesis for 3D Pose Estimation via a Smooth Silhouette Loss

github:
    model_url: https://github.com/VCL3D/DronePose
    repository_url: https://github.com/VCL3D/DronePose
    is_project_page: true
    repository_name: DronePose
    owner_url: https://github.com/tzole1155
    owner_name: Giorgos Albanis

google_analytics: UA-176089043-1
