theme: jekyll-theme-minimal
title: DronePose
description: This is the main project page of DronePose: Photorealistic UAV-Assistant Dataset Synthesis for 3D Pose Estimation via a Smooth Silhouette Loss
