theme: jekyll-theme-minimal
title: DronePose
show_downloads: true
description:

github:
    model_url: https://github.com/VCL3D/DronePose
    repository_url: https://github.com/VCL3D/DronePose
    is_project_page: true
    repository_name: DronePose
    owner_url: https://github.com/VCL3D
    owner_name: VCL3D
